name: upscalemp3
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version (TensorFlow 2.18 supports Python 3.9-3.12)
  - python=3.11
  
  # Core scientific packages (better to install via conda for optimized binaries)
  - numpy>=2.0.0
  - scipy>=1.11.4
  - matplotlib=3.10.1
  
  # Deep learning
  - tensorflow=2.18.0
  
  # Audio processing libraries available in conda
  - librosa=0.10.1
  - pywavelets=1.8.0
  - soundfile=0.12.1
  
  # Progress bars
  - tqdm=4.67.1
  
  # Protobuf
  - protobuf>=5.29.1
  
  # Pip dependencies (not available or better via pip)
  - pip
  - pip:
    - moviepy==1.0.3
    - pydub==0.25.1